### ISSUE TITLE
Does not seem to work on Mac

### ISSUE THREAD

**Issue by sabaatworld** [Rdiger-36/StudioBridge#2]
<img width="407" alt="Screenshot 2024-10-30 at 3 48 39 PM" src="https://github.com/user-attachments/assets/a1628058-fa29-4b09-8397-d4b04c179522">

I'm using the latest version of Bambu Studio.

**Comment by Rdiger-36** [comment]
Hi @sabaatworld it seems that Bambu Studio might use a port other than “2021” for connecting printers on macOS. I checked the Bambu Wiki, and I’ll add the alternative port “1990” to my program. Since I don’t have a macOS system, I couldn’t test it myself.

**Comment by Rdiger-36** [comment]
Hi @sabaatworld, it should work now with the new release update 1.0.2
